name       : xorg-driver-input-vmmouse
version    : 13.1.0
release    : 15
source     :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-input-vmmouse-13.1.0.tar.gz : 1a6c4a44b705f2c46d38c6ce17a4ffb4e37f4b6968bb827c59a2df3b65742831
license    :
    - MIT
summary    : VMMouse input driver
component  : xorg.driver
builddeps  :
    - pkgconfig(mtdev)
    - pkgconfig(xorg-server)
    - pkgconfig(xi)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
optimize   : no-bind-now
description: |
    The Xorg VMMouse Driver package contains the VMMouse input driver for the Xorg X server. The VMMouse driver enables support for the special VMMouse protocol that is provided by VMware virtual machines to give absolute pointer positioning.
setup      : |
    %configure --without-hal-callouts-dir \
               --with-udev-rules-dir=%libdir%/udev/rules.d \
               --without-hal-fdi-dir
build      : |
    %make
install    : |
    %make_install
